- hosts: local
  remote_user: root

  tasks:
    - include_vars: /etc/ansible/playbooks/packages.yml
    - yum: name={{item.name}} state=installed
      with_items: '{{packages}}'
      tags: Packages
      environment:
        http_proxy: http://endereço:8080
        https_proxy: http://endereço:8080
